# -*- coding: utf-8 -*-
"""Fifa19-EDA Saqlain Nazar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zx30tZYIvK6u4-D8dvrTmoJXbRfwUMK_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('fifa_eda.csv')

df.head()

df.isnull().sum()

plt.figure(figsize=(12,6))
sns.heatmap(df.isnull(), cbar=False)
plt.show()

df.duplicated().sum()

numeric = df.select_dtypes(include=np.number)

numeric.hist(figsize=(20,15))
plt.show()

plt.figure(figsize=(15,10))

sns.heatmap(
    numeric.corr(),
    cmap="coolwarm"
)

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["Overall"], bins=30)

plt.show()

plt.figure(figsize=(12,6))

df["Nationality"].value_counts().head(10).plot(kind="bar")

plt.title("Top 10 Nationalities")

plt.show()

sns.countplot(data=df, x="Preferred Foot")

plt.show()

plt.figure(figsize=(10,5))

sns.histplot(df["Age"], bins=20)

plt.show()

top = df.sort_values("Overall", ascending=False)

top[["Name","Overall","Club"]].head(10)

plt.figure(figsize=(12,6))

df["Club"].value_counts().head(10).plot(kind="bar")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["Overall"])

plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(
    data=df,
    x="Age",
    y="Overall"
)

plt.show()

sns.pairplot(
    df[["Age","Overall","Potential"]]
)

plt.show()

df.groupby("Preferred Foot")["Overall"].mean()